### ISSUE TITLE
Master node terminated

### ISSUE THREAD

**Issue by dabedin** [yorek/locust-on-azure#7]
I'm experiencing a new issue: the deployment script did not end as the master was not responding. The master ACI was in killing state, restarting it I collected the following log:
```
2020-11-01T18:01:36.3957911Z stderr F [2020-11-01 18:01:36,392] SandboxHost-637398500578781056/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
2020-11-01T18:01:36.4113665Z stderr F [2020-11-01 18:01:36,411] SandboxHost-637398500578781056/INFO/locust.main: Starting Locust 1.3.0
2020-11-01T18:01:36.4213724Z stderr F Traceback (most recent call last):
2020-11-01T18:01:36.4213724Z stderr F   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
2020-11-01T18:01:36.4213724Z stderr F   File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 391, in start_server
2020-11-01T18:01:36.4213724Z stderr F     self.server.serve_forever()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
2020-11-01T18:01:36.4333933Z stderr F     self.start()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
2020-11-01T18:01:36.4333933Z stderr F     self.init_socket()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1500, in init_socket
2020-11-01T18:01:36.4333933Z stderr F     StreamServer.init_socket(self)
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
2020-11-01T18:01:36.4333933Z stderr F     self.socket = self.get_listener(self.address, self.backlog, self.family)
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
2020-11-01T18:01:36.4333933Z stderr F     return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 284, in _tcp_listener
2020-11-01T18:01:36.4333933Z stderr F     sock = GeventSocket(family=family)
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 142, in __init__
2020-11-01T18:01:36.4333933Z stderr F     self._sock = self._gevent_sock_class(family, type, proto, fileno)
2020-11-01T18:01:36.4333933Z stderr F OSError: [Errno 97] Address family not supported by protocol
2020-11-01T18:01:36.4333933Z stderr F 2020-11-01T18:01:36Z <Greenlet at 0x7f4754fa1150: <bound method WebUI.start_server of <locust.web.WebUI object at 0x7f4754f89220>>> failed with OSError
2020-11-01T18:01:36.4333933Z stderr F 
2020-11-01T18:01:36.4333933Z stderr F [2020-11-01 18:01:36,425] SandboxHost-637398500578781056/CRITICAL/locust.web: Unhandled exception in greenlet: <Greenlet at 0x7f4754fa1150: <bound method WebUI.start_server of <locust.web.WebUI object at 0x7f4754f89220>>>
2020-11-01T18:01:36.4333933Z stderr F Traceback (most recent call last):
2020-11-01T18:01:36.4333933Z stderr F   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 391, in start_server
2020-11-01T18:01:36.4333933Z stderr F     self.server.serve_forever()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
2020-11-01T18:01:36.4333933Z stderr F     self.start()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
2020-11-01T18:01:36.4333933Z stderr F     self.init_socket()
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1500, in init_socket
2020-11-01T18:01:36.4333933Z stderr F     StreamServer.init_socket(self)
2020-11-01T18:01:36.4333933Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
2020-11-01T18:01:36.4333933Z stderr F     self.socket = self.get_listener(self.address, self.backlog, self.family)
2020-11-01T18:01:36.4343783Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
2020-11-01T18:01:36.4343783Z stderr F     return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
2020-11-01T18:01:36.4343783Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 284, in _tcp_listener
2020-11-01T18:01:36.4343783Z stderr F     sock = GeventSocket(family=family)
2020-11-01T18:01:36.4343783Z stderr F   File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 142, in __init__
2020-11-01T18:01:36.4343783Z stderr F     self._sock = self._gevent_sock_class(family, type, proto, fileno)
2020-11-01T18:01:36.4343783Z stderr F OSError: [Errno 97] Address family not supported by protocol
2020-11-01T18:01:36.4343783Z stderr F [2020-11-01 18:01:36,426] SandboxHost-637398500578781056/INFO/locust.main: Running teardowns...
2020-11-01T18:01:36.9293872Z stderr F [2020-11-01 18:01:36,929] SandboxHost-637398500578781056/INFO/locust.main: Shutting down (exit code 2), bye.
2020-11-01T18:01:36.9293872Z stderr F [2020-11-01 18:01:36,930] SandboxHost-637398500578781056/INFO/locust.main: Cleaning up runner...
```
Any idea on this?

**Comment by yorek** [comment]
Uh haven't happed to me this yet....I used locust on ACI a lot lately and usually I had problem with just ACI in general, where some container was stuck in an infinite reboot loop. This problem, not yet....

**Comment by dabedin** [comment]
That is strange, I encounter the error only on the internal subscription, not on my own personal one. I will investigate

**Comment by yorek** [comment]
@dabedin s this still happening, or the issue can be closed?i

**Comment by dabedin** [comment]
Did not happen again, it can be closed
